### ISSUE TITLE
Options url and schema config entry

### ISSUE THREAD

**Issue by LesegoMohaule** [kartoza/GeoContextQGISPlugin#10]
I think these should be hard coded or there should be a drop down menu that gives options of selecting them or entering your preferred valid url and schema config.
![image](https://user-images.githubusercontent.com/69116236/147253074-7cfcfa40-fa21-4a28-aff0-a192612aaa8c.png)

**Comment by vermeulendivan** [comment]
This should be changable for when someone else (outside Kartoza) what's to use geocontext and the geocontext plugin for there own map viewer and website. So these values needs to be changable. We should rather add a check for an error which clearly explains the issue to the user.
