### ISSUE TITLE
Elevation value of random vector point is null

### ISSUE THREAD

**Issue by LesegoMohaule** [kartoza/GeoContextQGISPlugin#11]
Elevation value of random vector point is null after field has been created via the elevation key of the processing tool
![image](https://user-images.githubusercontent.com/69116236/147253266-179234ef-cc03-41ec-8b0c-dcae9cfea4e6.png)

**Comment by vermeulendivan** [comment]
Where is the random point situated? If its outside SA, it will result in a nodata value.
