### ISSUE TITLE
GeoContextPlugin Processing tool not processing

### ISSUE THREAD

**Issue by LesegoMohaule** [kartoza/GeoContextQGISPlugin#12]
Processing tool does not execute when I select 2012 Biome Map of South Africa, Lesotho and Swaziland on selected countries. Image attached
![image](https://user-images.githubusercontent.com/69116236/147253431-8aeadc64-bc09-4add-a0f9-9bff66b81fb5.png)

**Comment by vermeulendivan** [comment]
I did this, but not getting the same issue. From the printscreen the layer seems to be polygon, maybe the cause? Also, Qt designer has an issue when changing the input to only accept point vector files. The course I did the tutor also pointed out the glitch, and then showed how to do that within the code - just need to find the slides which explains how to do it.
