### ISSUE TITLE
Plugin only works on correct crs vector maps 

### ISSUE THREAD

**Issue by LesegoMohaule** [kartoza/GeoContextQGISPlugin#13]
I tested the plugin with my Helen Dallas project map and because the longitude and latitude coordinates were correctly referenced it yielded some results. I think that the plugin should work regardless of the crs of the canvas or whether it is a vector or raster layer. It should auto correct to give the right results. If it is used on a raster canvas or other crs it throws an error. Here is a snapshot of the test with the right results
![Test on Helen Dallas project map](https://user-images.githubusercontent.com/69116236/147353136-c147bd58-ceb5-456d-b497-c743f1bf8941.PNG)

**Comment by vermeulendivan** [comment]
This has been resolved
