### ISSUE TITLE
Processing tool does not generate output file unless suffix is specified as either .gpkg or .shp

### ISSUE THREAD

**Issue by LesegoMohaule** [kartoza/GeoContextQGISPlugin#9]
I suggest that a default output should be generated and the user should then have the option to choose the file format of the output file they would like to save or export

**Comment by vermeulendivan** [comment]
The tool has now been set up to add ".gpkg" if not provided for a file format. Shapefile will now be excluded, as it is an old format. Inputs can still be shp, and other formats should also work. Only affecting the output.
